/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TFooter: typeof import('./src/components/t-footer.vue')['default']
    THeader: typeof import('./src/components/t-header.vue')['default']
    TLoading: typeof import('./src/components/t-loading.vue')['default']
    TQuestionList: typeof import('./src/components/t-question-list.vue')['default']
    TSelectLevel: typeof import('./src/components/t-select-level.vue')['default']
  }
}
